# Generated by Django 5.2.5 on 2025-08-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_profile_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="clerk_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_image_url",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
